name: movie_mania
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dotted_border: ^2.1.0
  http: ^1.1.0
  image_picker: ^1.0.7
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
